### ISSUE TITLE
There has been a critical error on this website. Please check your site admin email inbox for instructions.

### ISSUE THREAD

**Issue by drooban** [dtbaker/stylepress#48]
How do I fix the issue?

My existing styles are not showing. I don't know why it happens

Can you please help me?

**Comment by cory-github** [comment]
I get this same error as well. I think this stylepress just isn't compatible with new wordpress or something? This stylepress hasn't been updated for 2 years according to the wordpress plugins page. This really sucks as while the website I have it on still works, I am unable to make any changes to the stylepress portions of the layout. Really hoping the developer will comment.

**Comment by ctrlj-dev** [comment]
Hi, I think I have fixed the error. The problem is that StylePress was not generating the Elementor edit link, I suppose, due to some change in the Elementor core. I have changed that link, and now everything works correctly. 

The solution:

Go to plugins/full-site-builder-for-elementor/admin/styles-page-inner.php on line 125

Yo will see this: 
```

<tr>
    <td>
        <a class="" href="<?php echo esc_url(\Elementor\Utils::get_edit_link($style->ID)); ?>"><?php echo esc_html($style->post_title); ?></a>
    </td>
    <td>
        <a href="<?php echo esc_url(admin_url('admin.php?page=dtbaker-stylepress-settings')); ?>">
            <?php if ($used) { ?>
                <i class="fa fa-check"></i> Style Applied To: <?php echo implode(', ', $used); ?>.
            <?php } else { ?>
                <i class="fa fa-times"></i> Style Not Used.
            <?php } ?>
        </a>
    </td>
    <td>
        <a class="button button" href="<?php echo esc_url(get_edit_post_link($style->ID)); ?>">Settings</a>
        <a class="button button" href="<?php print wp_nonce_url(admin_url('admin.php?action=stylepress_clone&post_id=' . (int) $style->ID), 'stylepress_clone', 'stylepress_clone'); ?>"><?php esc_html_e('Clone', 'stylepress'); ?></a>
        <a class="button button" href="<?php echo esc_url(get_permalink($style->ID)); ?>"><?php esc_html_e('Preview', 'stylepress'); ?></a>
        <a class="button button-primary" href="<?php echo esc_url(\Elementor\Utils::get_edit_link($style->ID)); ?>"><?php esc_html_e('Elementor', 'stylepress'); ?></a>
    </td>
</tr>
```

From 125 to 149...

You just have to replace it with this:

```
<tr>
    <td>
        <a class="" href="<?php echo esc_url('post.php?post=' . (int) $style->ID . '&action=elementor'); ?>"><?php echo esc_html($style->post_title); ?></a>
    </td>
    <td>
        <a href="<?php echo esc_url(admin_url('admin.php?page=dtbaker-stylepress-settings')); ?>">
            <?php if ($used) { ?>
                <i class="fa fa-check"></i> Style Applied To: <?php echo implode(', ', $used); ?>.
            <?php } else { ?>
                <i class="fa fa-times"></i> Style Not Used.
            <?php   } ?>
        </a>
    </td>
    <td>
        <a class="button button" href="<?php echo esc_url(get_edit_post_link($style->ID)); ?>">Settings</a>
        <a class="button button" href="<?php print wp_nonce_url(admin_url('admin.php?action=stylepress_clone&post_id=' . (int) $style->ID), 'stylepress_clone', 'stylepress_clone'); ?>"><?php esc_html_e('Clone', 'stylepress'); ?></a>
        <a class="button button" href="<?php echo esc_url(get_permalink($style->ID)); ?>"><?php esc_html_e('Preview', 'stylepress'); ?></a>
        <a class="button button-primary" href="<?php echo esc_url('post.php?post=' . (int) $style->ID . '&action=elementor'); ?>"><?php esc_html_e('Elementor', 'stylepress'); ?></a>
    </td>
</tr>
```

Make a backup before trying it.

**Comment by cory-github** [comment]
@ctrlj-dev - Thank you very much. I have done this and it now allows me to edit the couple style templates I had for some pages and make the changes I was looking to make. After I also updated wordpress to the latest version, as well as all of the plugins (including a big Elementor one), and so far still looks to load.

I do notice however that when going in to StylePress > Styles, and then clicking on "Edit Style" button for a style, it is still showing an error message. So the "Outer Style" section loads, this is the part where I can click "Elementor" and make the changes I mentioned. 
But in the lower section "Inner Styles" it shows "There has been a critical error on this website. Please check your site admin email inbox for instructions"; and, I received an email "Your Site is Experiencing a Technical Issue".
I have two outer styles on the site, the one gives this error and the other doesn't (presumably I don't have an Inner Style).

`Error Details
=============
An error of type E_ERROR was caused in line 194 of the file /<site>/wp-content/plugins/full-site-builder-for-elementor/admin/styles-page-inner.php. Error message: Uncaught Error: Call to undefined method Elementor\Utils::get_edit_link() in /home/lieversc/public_html/fieldlieversarchitecture.ca/wp-content/plugins/full-site-builder-for-elementor/admin/styles-page-inner.php:194
Stack trace:
#0 /<site>/wp-content/plugins/full-site-builder-for-elementor/admin/styles-page.php(32): require_once()
#1 /<site>/wp-content/plugins/full-site-builder-for-elementor/inc/class.plugin.php(802): include('/home/user/...')
#2 /<site>/wp-includes/class-wp-hook.php(287): DtbakerElementorManager->styles_page_callback('')
#3 /<site>/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#4 /<site>/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#5 /<site>/wp-admin/admin.php(259): do_action('`


I took a screenshot and tried uploading as image on this post as well.

![error1](https://user-images.githubusercontent.com/5701302/116749885-d5c0e100-a9be-11eb-9f4f-163a8c0116ca.png)
![error2](https://user-images.githubusercontent.com/5701302/116750182-4d8f0b80-a9bf-11eb-899c-10bc3a04ff21.png)

**Comment by Dhamoseo** [comment]
Any new update about stylepress plugin. I want to update some changes. Can
you please help me?
